name: aimex
description: "AIMEX sales & inventory app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Icons
  cupertino_icons: ^1.0.8

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Excel Export
  excel: ^2.1.0
  file_picker: ^8.0.0+1
  
  # Share
  share_plus: ^7.2.2

  # UUID
  uuid: ^4.3.3

  # Date Formatting
  intl: ^0.19.0

  # Notifications
  fluttertoast: ^8.2.4
  flutter_local_notifications: ^20.1.0
  workmanager: ^0.9.0
  shared_preferences: ^2.2.2

  # Permissions
  permission_handler: ^11.0.1

  # PDF
  pdf: ^3.10.8
  printing: ^5.12.0

  # Zip Compression
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Hive Code Generator
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
